version: '3.3'

services:
  database:
    image: postgres:13
    environment:
      - POSTGRES_DB=my_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=12345
    ports:
      - '8080:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql


