version: '3.7'

services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - database
    environment:
      DB: '$DB'
      DB_USERNAME: '$DB_USERNAME'
      DB_PASSWORD: '$DB_PASSWORD'
      
    ports:
      - "9000:3000"
  database:
    image: postgres:13
    environment:
      POSTGRES_DB: "${DB}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    ports:
      - '4000:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql


